version: '3'
services:  
  php:    
    image: php:8.0.7-apache
    container_name: php-apache
    volumes:
      - ./html:/var/www/html
    restart: always
    ports:
      - "1080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1qaz2wsx"
    volumes:
      - ./data/db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 1qaz2wsx
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
